CREATE TABLE "HOTELDAPA"."GENERAL_CLIENTES" 
   (	"GEN_CLI_COD" VARCHAR2(11 CHAR) NOT NULL ENABLE, 
	"GEN_CLI_SUCCOD" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"GEN_CLI_NOM1" VARCHAR2(60 CHAR), 
	"GEN_CLI_TIPCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_CONT" VARCHAR2(30 CHAR), 
	"GEN_CLI_CONTCARGO" VARCHAR2(30 CHAR), 
	"GEN_CLI_CONTTEL" VARCHAR2(12 CHAR), 
	"GEN_CLI_SUCNOM" VARCHAR2(30 CHAR), 
	"GEN_CLI_SUCDIR" VARCHAR2(75 CHAR), 
	"GEN_CLI_SUCTEL" VARCHAR2(15 CHAR), 
	"GEN_CLI_SUCFAX" VARCHAR2(12 CHAR), 
	"GEN_CLI_VENCOD" VARCHAR2(11 CHAR), 
	"GEN_CLI_PAICOD" VARCHAR2(4 CHAR), 
	"GEN_CLI_DPTCOD" VARCHAR2(4 CHAR), 
	"GEN_CLI_MPOCOD" VARCHAR2(5 CHAR), 
	"GEN_CLI_CNACOD" VARCHAR2(4 CHAR), 
	"GEN_CLI_BARCOD" VARCHAR2(8 CHAR), 
	"GEN_CLI_ZONCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_CUPCRE" NUMBER(17,2), 
	"GEN_CLI_FORPAG" VARCHAR2(3 CHAR), 
	"GEN_CLI_LISPRE" VARCHAR2(8 CHAR), 
	"GEN_CLI_PORDES" NUMBER(6,3), 
	"GEN_CLI_DESCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_AUTRET" VARCHAR2(1 CHAR), 
	"GEN_CLI_APLINT" VARCHAR2(1 CHAR), 
	"GEN_CLI_PORINT" NUMBER(6,2), 
	"GEN_CLI_ACTIVO" VARCHAR2(1 CHAR), 
	"GEN_CLI_BLOQ" VARCHAR2(1 CHAR), 
	"GEN_CLI_REPOR" VARCHAR2(1 CHAR), 
	"GEN_CLI_FECRPTRIS" DATE, 
	"GEN_CLI_FECAPERT" DATE, 
	"GEN_CLI_GRUCOD" VARCHAR2(3 CHAR), 
	"GEN_EMP_PAIS" VARCHAR2(4 CHAR), 
	"GEN_EMP_COD" VARCHAR2(20 CHAR), 
	"GEN_CLI_CEUCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_SCUCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_CCOCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_SCOCOD" VARCHAR2(3 CHAR), 
	"GEN_CLI_MAIL" VARCHAR2(50 CHAR), 
	"GEN_CLI_MOVIL" VARCHAR2(1 CHAR), 
	"GEN_CLI_OMTPAG" VARCHAR2(1 CHAR), 
	"GEN_CLI_PORICA" NUMBER(6,3), 
	"GEN_CLI_DIRENT" VARCHAR2(75 CHAR), 
	 PRIMARY KEY ("GEN_CLI_COD", "GEN_CLI_SUCCOD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;